Garage_2_0/Models/Member.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Garage_2_0.Models
{
    public class Member
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public ICollection<Vehicle> Vehicles { get; set; }
    }
}

Garage_2_0/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage_2_0.Models;

namespace Garage_2_0.Controllers
{
    public class MembersController : Controller
    {
        private readonly Garage_2_0Context _context;

        public MembersController(Garage_2_0Context context)
        {
            _context = context;
        }

        // GET: Members
        public async Task<IActionResult> Index()
        {
                return View(await _context.Members
                    .Include(m => m.Vehicles)
                    .OrderBy(m => m.Name)
                    .ToListAsync());
        }

        public ActionResult IndexSort(string sortOrder)            // sort columns ascendiong/descending
        {
            ViewBag.NamnSortParm = String.IsNullOrEmpty(sortOrder) ? "Namn" : "";

            var members = from m in _context.Members select m;

            switch (sortOrder)
            {
                case "Namn":
                    members = members.OrderBy(m => m.Name);
                    break;
                    //Vi behöver också sortera på antalet fordon
            }
            return View(nameof(Index), members.Include(m => m.Vehicles).ToList());
        }

        // GET: RegNr                                           // sökning regnr, searchTerm innehåller sökvärdet, funktionen anropas från index.cshtml
        [HttpPost]
        public ActionResult Index(string searchTerm = null)
        {
            var model =
                _context.Members
                .OrderByDescending(m => m.Name)
                .Where(m => searchTerm == null || m.Name.StartsWith(searchTerm) || m.Name.Contains(searchTerm))
                .Include(m => m.Vehicles)
                .ToList();
            return View(model);
        }

        public ActionResult Index1(string columnToSort, Garage_2_0Context.MembersSortState sortState )            // sort columns ascendiong/descending
        {

            var members = from m in _context.Members select m;
            members = members.Include(m => m.Vehicles);

            if (columnToSort == "Namn")
            {
                if (sortState == Garage_2_0Context.MembersSortState.NamnAscend)
                {
                    members = members.OrderByDescending(m => m.Name);
                    ViewBag.sortState = Garage_2_0Context.MembersSortState.NamnDescend;
                }
                else
                {
                    members = members.OrderBy(m => m.Name);
                    ViewBag.sortState = Garage_2_0Context.MembersSortState.NamnAscend;
                }
            }
            else if (columnToSort == "Antal Fordon")
            {
                if (sortState == Garage_2_0Context.MembersSortState.AntalFordonAscend)
                {
                    members = members.OrderByDescending(m => m.Vehicles.Count);
                    ViewBag.sortState = Garage_2_0Context.MembersSortState.AntalFordonDescend;
                }
                else
                {
                    members = members.OrderBy(m => m.Vehicles.Count);
                    ViewBag.sortState = Garage_2_0Context.MembersSortState.AntalFordonAscend;
                }
            }
            return View(nameof(Index), members.ToList());
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .Include(m => m.Vehicles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Member member)
        {
            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Member member)
        {
            if (id != member.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var member = await _context.Members.FindAsync(id);
            _context.Members.Remove(member);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(int id)
        {
            return _context.Members.Any(e => e.Id == id);
        }
    }
}

Garage_2_0/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage_2_0.Models;
using Garage_2_0.ViewModels;

namespace Garage_2_0.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly Garage_2_0Context _context;

        public VehiclesController(Garage_2_0Context context)
        {
            _context = context;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            var model = await _context.Vehicles.Include(v => v.VehicleTypeClass).Select(v => new VehiclesViewModel
            {
                Id = v.Id,
                MemberName = v.Member.Name,
                Brand = v.Brand,
                Color = v.Color,
                Model = v.Model,
                ParkingTime = Extensions.VehicleExtension.ParkingTime(v),
                NoWheels = v.NoWheels,
                RegNr = v.RegNr,
                VehicleTypeClass = v.VehicleTypeClass,
                SearchTerm = ""
            }).OrderBy( v => v.RegNr ).ToListAsync();

            ViewBag.sortState = Garage_2_0Context.VehiclesSortState.RegNrAscend;

            return View(model);

        }

        // POST: Search for RegNr                             // sökning regnr, searchTerm innehåller sökvärdet, funktionen anropas från index.cshtml
        [HttpPost]
        public ActionResult Index(string searchTerm = null)
        {
            var model = _context.Vehicles
                .Include(v => v.VehicleTypeClass)
                .Select(v => new VehiclesViewModel
                    {
                        Id = v.Id,
                        MemberName = v.Member.Name,
                        Brand = v.Brand,
                        Color = v.Color,
                        Model = v.Model,
                        ParkingTime = Extensions.VehicleExtension.ParkingTime(v),
                        NoWheels = v.NoWheels,
                        RegNr = v.RegNr,
                        VehicleTypeClass = v.VehicleTypeClass,
                        SearchTerm = ""
                    })
                .Where(v => searchTerm == null || v.RegNr.StartsWith(searchTerm) || v.RegNr.Contains(searchTerm))
                .OrderBy(v => v.RegNr)
                .ToList();

            ViewBag.sortState = Garage_2_0Context.VehiclesSortState.RegNrAscend;

            return View(model);
        }


        public ActionResult Index1(string columnToSort, Garage_2_0Context.VehiclesSortState sortState)            // sort columns ascendiong/descending
        {
            var model = _context.Vehicles.Include(v => v.VehicleTypeClass).Select(v => new VehiclesViewModel
            {
                Id = v.Id,
                MemberName = v.Member.Name,
                Brand = v.Brand,
                Color = v.Color,
                Model = v.Model,
                ParkingTime = Extensions.VehicleExtension.ParkingTime(v),
                NoWheels = v.NoWheels,
                RegNr = v.RegNr,
                VehicleTypeClass = v.VehicleTypeClass,
                SearchTerm = ""
            });

            switch (columnToSort)
            {
                case "Member":
                    if (sortState == Garage_2_0Context.VehiclesSortState.MemberAscend)
                    {
                        model = model.OrderByDescending(v => v.MemberName);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.MemberDescend;
                    }
                    else
                    {
                        model = model.OrderBy(v => v.MemberName);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.MemberAscend;
                    }
                    break;
                case "Type":
                    if (sortState == Garage_2_0Context.VehiclesSortState.TypeAscend)
                    {
                        model = model.OrderByDescending(v => v.VehicleTypeClass.Type);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.TypeDescend;
                    }
                    else
                    {
                        model = model.OrderBy(v => v.VehicleTypeClass.Type);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.TypeAscend;
                    }
                    break;
                case "RegNr":
                    if (sortState == Garage_2_0Context.VehiclesSortState.RegNrAscend)
                    {
                        model = model.OrderByDescending(v => v.RegNr);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.RegNrDescend;
                    }
                    else
                    {
                        model = model.OrderBy(v => v.RegNr);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.RegNrAscend;
                    }
                    break;
                case "Color":
                    if (sortState == Garage_2_0Context.VehiclesSortState.ColorAscend)
                    {
                        model = model.OrderByDescending(v => v.Color);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.ColorDescend;
                    }
                    else
                    {
                        model = model.OrderBy(v => v.Color);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.ColorAscend;
                    }
                    break;
                case "Brand":
                    if (sortState == Garage_2_0Context.VehiclesSortState.BrandAscend)
                    {
                        model = model.OrderByDescending(v => v.Brand);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.BrandDescend;
                    }
                    else
                    {
                        model = model.OrderBy(v => v.Brand);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.BrandAscend;
                    }
                    break;
                case "Model":
                    if (sortState == Garage_2_0Context.VehiclesSortState.ModelAscend)
                    {
                        model = model.OrderByDescending(v => v.Model);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.ModelDescend;
                    }
                    else
                    {
                        model = model.OrderBy(v => v.Model);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.ModelAscend;
                    }
                    break;
                case "NoWheels":
                    if (sortState == Garage_2_0Context.VehiclesSortState.NoWheelsAscend)
                    {
                        model = model.OrderByDescending(v => v.NoWheels);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.NoWheelsDescend;
                    }
                    else
                    {
                        model = model.OrderBy(v => v.NoWheels);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.NoWheelsAscend;
                    }
                    break;
                case "ParkingTime":
                    if (sortState == Garage_2_0Context.VehiclesSortState.ParkingTimeAscend)
                    {
                        model = model.OrderByDescending(v => v.ParkingTime);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.ParkingTimeDescend;
                    }
                    else
                    {
                        model = model.OrderBy(v => v.ParkingTime);
                        ViewBag.sortState = Garage_2_0Context.VehiclesSortState.ParkingTimeAscend;
                    }
                    break;
            }   
            return View(nameof(Index), model.ToList());
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .Include( v => v.Member)
                .Include( v => v.VehicleTypeClass)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            ViewBag.MemberSelectList = _context.Members.OrderBy(m=>m.Name).Select(m => new SelectListItem { Selected = false, Text = m.Name, Value = m.Id.ToString() }).ToList();
            ViewBag.VehicleTypeSelectList = _context.VehicleTypeClass.Select(t => new SelectListItem { Selected = false, Text = t.Type, Value = t.Id.ToString() }).ToList();

            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RegNr,Color,Brand,Model,NoWheels,MemberId,VehicleTypeClassId")] Vehicle vehicle)
        {
            if (RegNoIsParked(vehicle.RegNr))
                ModelState.AddModelError("RegNr", "Det finns redan ett fordon med det här registreringsnumret i garaget");

            if (ModelState.IsValid)
            {
                vehicle.ParkedIn = DateTime.Now;
                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

Garage_2_0/Views/Members/Create.cshtml
@model Garage_2_0.Models.Member

@{
    ViewData["Title"] = "Create";
}

<h1>Lägg till</h1>

<h4>Medlem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Namn</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lägg till" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka till medlemslistan</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage_2_0/Views/Members/Delete.cshtml
@model Garage_2_0.Models.Member

@{
    ViewData["Title"] = "Delete";
}

<h1>Ta bort</h1>

<h3>Är Du säker på att ta bort denna medlem?</h3>
<div>
    <h4>Medlem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Name)*@
            Medlem
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Ta bort" class="btn btn-danger" /> |
        <a asp-action="Index">Tillbaka till medlemslistan</a>
    </form>
</div>

Garage_2_0/Views/Members/Details.cshtml
@model Garage_2_0.Models.Member

@{
    ViewData["Title"] = "´Detaljvy";
}

<h1>Detaljvy</h1>

<div>
    <h4>Medlem</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
           Medlem
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">Fordon</dt>
        <dd class="col-md-10">
            @foreach (var vehicle in Model.Vehicles)
            {
                <a asp-controller="Vehicles" asp-action="Details" asp-route-id="@vehicle.Id">
                    @vehicle.RegNr
                </a><br />
            }
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Ändra</a> |
    <a asp-action="Index">Tillbaka till medlemslistan</a>
</div>

Garage_2_0/Views/Members/Edit.cshtml
@model Garage_2_0.Models.Member

@{
    ViewData["Title"] = "Edit";
}

<h1>Ändra</h1>

<h4>Medlem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Namn</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spara ändring" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka till medlemslistan</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage_2_0/Views/Members/Index.cshtml
@model IEnumerable<Garage_2_0.Models.Member>

@{
    ViewData["Title"] = "Index";
}

<h1>Medlemmar</h1>

<form asp-action="Index" method="post">
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="searchTerm" placeholder="Sök på hela eller del av namnet" />
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary"> Sök </button>
        </div>
    </div>
</form>

<p>
    <a asp-action="Create">Lägg till ny medlem</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Namn", "Index1", new { columnToSort = "Namn", sortState = ViewBag.sortState } )
            </th>
            <th>
                @Html.ActionLink("Antal Fordon", "Index1", new { columnToSort = "Antal Fordon", sortState = ViewBag.sortState } )
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @item.Vehicles.Count
                </td>
                <td>
                    @*<a asp-action="Edit" asp-route-id="@item.Id">Ändra</a> |*@
                    <a asp-action="Details" asp-route-id="@item.Id">Mer fakta</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Ta bort</a>
                </td>
            </tr>
        }
    </tbody>
</table>